[package]
name = "duct"
version = "0.4.0"
authors = ["oconnor663@gmail.com"]
description = "a library for creating shell pipelines"
repository = "https://github.com/oconnor663/duct.rs"
license = "MIT"

[dependencies]
os_pipe = "^0.2"
crossbeam = ">=0.2.8"

[dev-dependencies]
tempfile = ">=2.1.1"
tempdir = ">=0.3.4"
