[package]
name = "duct"
version = "0.9.0"
authors = ["oconnor663@gmail.com"]
description = "a library for creating shell pipelines"
repository = "https://github.com/oconnor663/duct.rs"
documentation = "https://docs.rs/duct"
license = "MIT"

[dependencies]
os_pipe = "^0.5.1"
shared_child = "^0.3.2"
lazycell = "^0.5.0"

[target.'cfg(unix)'.dependencies]
libc = "^0.2.20"

[dev-dependencies]
tempdir = "^0.3.4"
