[package]
name = "duct"
version = "0.1.0"
authors = ["oconnor663@gmail.com"]
description = "a library for creating shell pipelines"
repository = "https://github.com/oconnor663/duct.rs"
license = "MIT"
